app = 'midday-worker-staging'
primary_region = 'fra'

[build]

[env]
  NODE_ENV = 'production'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 3

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.checks]]
    grace_period = "10s"
    interval = "45s"
    method = "GET"
    timeout = "10s"
    path = "/health"

# VM configuration for worker process
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

