compatibility_date = "2024-11-11"
workers_dev = false
logpush = true
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true


[env.production]
name = "engine"
route = { pattern = "engine.er0s.co/*", zone_name = "er0s.co" }

kv_namespaces = [
  { binding = "KV", id = "1ce9f0355d854a569f72bfccbfbea369" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "76fdbac8-e96b-4a1e-922c-e54891b7371c" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "", jurisdiction = "eu" }
]

[env.production.ai]
binding = "AI"
provider = "llama"
model = "llama-3.3"
jurisdiction = "eu"

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.er0s.co/*", zone_name = "er0s.co" }

kv_namespaces = [
  { binding = "KV", id = "825dc18b2a38463492ff0db06ba99fc8" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "76fdbac8-e96b-4a1e-922c-e54891b7371c" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "", jurisdiction = "eu" }
]

[env.staging.ai]
binding = "AI"
provider = "llama"
model = "llama-3.3"
jurisdiction = "eu"