name = "logdrain"
main = "src/worker.ts"
compatibility_date = "2024-01-17"

node_compat = true


routes = [
 { pattern = "logdrain.solomon-ai-platform.com", custom_domain = true},
]

[vars]
AXIOM_TOKEN = "xaat-be1de990-77ee-449b-8e57-9c56173b2869"
AXIOM_ORG_ID = "solomon-ai-hqno"