name: Preview Deployment - Website
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEBSITE }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
on:
  push:
    branches-ignore:
      - main
    paths:
      - apps/website/**
      - packages/**
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate slug
        uses: rlespinasse/github-slug-action@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.29"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      # - name: ðŸ”¦ Run linter
      #   run: bun run lint --filter=@midday/website
      # - name: ðŸª Check TypeScript
      #   run: bun run typecheck --filter=@midday/website
      - name: ðŸ“¤ Pull Vercel Environment Information
        run: bunx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: ðŸ— Build Project Artifacts
        run: bunx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          bunx vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          bunx vercel alias --scope=${{ secrets.VERCEL_ORG_ID }} --token=${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` ${{ env.GITHUB_REF_SLUG }}.midday.ai
